import Head from "next/head";
import Container from "react-bootstrap/Container";
import PageHeader from "../components/PageHeader";

export default function About() {
  return (
    <>
      <Head>
        <title>About Us - FRC Team 2658</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageHeader title="About Us" />
    </>
  );
}
