import Head from "next/head";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Header from "../components/PageHeader";

// import styles from "../styles/contactPage.module.css";
import ContactForm from "../components/ContactForm";
//import ContactInfo from "../components/ContactInfo";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact Us - FRC Team 2658</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header title="Contact Us" />
      <Container>
        <Row>
          <Col>
            <ContactForm />
          </Col>
          {/* 

          <Col>
            <ContactInfo />
          </Col>

          */}
        </Row>
      </Container>
    </>
  );
}
